export const projects = [{
        title: "Airline Database (Oracle SQL)",
        desc: "Designed a relational database for flights, seats, staff and reports. Built from ERD and populated with sample data; includes practical queries and summaries.",
        tags: ["SQL", "Oracle", "Reports"],
        repo: "https://github.com/slqf25/Airline-Analysis-Report",
        category: "database",
        year: "Dec 2024",
    },
    {
        title: "Celestial Airline Route Planner (Java)",
        desc: "Command-line planner to find flight connections and routes. Data is saved to files so results can be reused; simple menus and clear prompts.",
        tags: ["Java", "Routing", "File I/O"],
        repo: "https://github.com/slqf25/Celestial_Airline",
        category: "java",
        year: "Sept 2025",
    },
    {
        title: "Hotel Management Console (Java)",
        desc: "A simple console system to manage rooms, bookings, guests and payments. Focus on clean menus and printable summaries for quick checks.",
        tags: ["Java", "Console", "Reports"],
        repo: "https://github.com/slqf25/Celestial-Hotel-Management-System",
        category: "java",
        year: "May 2025",
    },
    {
        title: "Wedding Management Console (C++)",
        desc: "Keeps track of packages, customers, schedules and payments in one place. Designed to be easy to update and search from the keyboard.",
        tags: ["C++", "Console"],
        repo: "https://github.com/slqf25/wedding-management",
        category: "cpp",
        year: "Sept 2025",
    },
    {
        title: "Train Ticketing System (C++)",
        desc: "Lets users pick routes, calculate fares and print tickets in a simple text interface. Stores data so bookings can be reviewed later.",
        tags: ["C++", "Console", "Bookings"],
        repo: "https://github.com/slqf25/Train-Ticketing-System",
        category: "cpp",
        year: "Sept 2024",
    },
    {
        title: "Exam Guide System (Python)",
        desc: "A small tool to organise study topics and quick notes. Add, browse and search guides from the terminal; ideal for revision checklists.",
        tags: ["Python", "Console"],
        repo: "https://github.com/slqf25/Exam-Guide",
        category: "python",
        year: "Dec 2025",
    },
];