export const projects = [{
        title: 'Airline Database Management (Oracle SQL)',
        desc: 'ERD → DDL/DML with sample data; staff/seat/flight modules; SQL reports.',
        tags: ['SQL', 'Oracle', 'ERD', 'DDL/DML'],
        repo: 'https://github.com/slqf25/Airline-Analysis-Report',
        category: 'database',
        year: 2025,
    },
    {
        title: 'Celestial Airline Route Planner (Java)',
        desc: 'Adjacency-list flight graph with BFS traversal; CSV persistence; CLI.',
        tags: ['Java', 'Graph', 'BFS', 'File I/O'],
        repo: 'https://github.com/slqf25/Celestial_Airline',
        category: 'java',
        year: 2025,
    },
    {
        title: 'Hotel Management Console (Java)',
        desc: 'OOP console app: rooms, booking, guests, payments, revenue reports.',
        tags: ['Java', 'OOP', 'Console', 'Reports'],
        repo: 'https://github.com/slqf25/Celestial-Hotel-Management-System',
        category: 'java',
        year: 2025,
    },
    {
        title: 'Wedding Management Console (C++)',
        desc: 'Booking, catalog, payments, guests & schedule; vectors/regex/file I/O.',
        tags: ['C++', 'Console', 'Vectors', 'Regex'],
        repo: 'https://github.com/slqf25/wedding-management',
        category: 'cpp',
        year: 2025,
    },
    {
        title: 'Train Ticketing System (C++)',
        desc: 'Ticket booking; routes/fares/seats; CLI with persistence.',
        tags: ['C++', 'Console', 'CRUD', 'Persistence'],
        repo: 'https://github.com/slqf25/Train-Ticketing-System',
        category: 'cpp',
        year: 2025,
    },
    {
        title: 'Exam Guide System (Python)',
        desc: 'Python CLI for study plan & question bank; file-based storage and search.',
        tags: ['Python', 'CLI', 'File I/O'],
        repo: 'https://github.com/slqf25/Exam-Guide',
        category: 'python',
        year: 2025,
    },
];